version: '3.5'

services:

  front-end:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    container_name: front-end
    ports:
      - '3001:3001'
    networks:
      - internal_network
    volumes:
      - ./front-end/src:/app/src


networks:
  internal_network:

volumes:
  pgdata_vol:
